package com.hotelvaluation.model

data class YearProjection(
    val year: Int,
    val occupancy: Double,
    val adr: Double,
    val revPar: Double,
    val roomRevenue: Double,
    val fbRevenue: Double,
    val otherRevenue: Double,
    val totalRevenue: Double,
    val roomsExpense: Double,
    val fbExpense: Double,
    val otherExpense: Double,
    val totalDeptExpense: Double,
    val departmentalProfit: Double,
    val adminGeneral: Double,
    val marketing: Double,
    val propOperations: Double,
    val utility: Double,
    val totalUndistributed: Double,
    val grossOperatingProfit: Double,
    val insurance: Double,
    val propertyTax: Double,
    val managementFee: Double,
    val franchiseFee: Double,
    val totalFixedCharges: Double,
    val ebitda: Double,
    val reserveForReplacement: Double,
    val netOperatingIncome: Double,
    val pipExpenditure: Double,
    val cashFlowAfterPip: Double,
    val discountFactor: Double,
    val presentValue: Double,
)

data class ValuationResult(
    val yearProjections: List<YearProjection>,
    val totalPvCashFlows: Double,
    val terminalValue: Double,
    val pvTerminalValue: Double,
    val totalPropertyValue: Double,
    val valuePerRoom: Double,
    val impliedCapRate: Double,
    val impliedMultiple: Double,
)
